"""initial_migration

Revision ID: 3a97e87815a3
Revises:
Create Date: 2026-04-17 11:16:53.282457

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a97e87815a3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="user_role"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("accounts_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("accounts_pkey")),
    )
    op.create_index(op.f("accounts_user_id_idx"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("payments_account_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("payments_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("payments_pkey")),
    )
    op.create_index(op.f("payments_account_id_idx"), "payments", ["account_id"], unique=False)
    op.create_index(
        op.f("payments_transaction_id_idx"), "payments", ["transaction_id"], unique=True
    )
    op.create_index(op.f("payments_user_id_idx"), "payments", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # Seed test data
    op.execute(
        sa.text(
            "INSERT INTO users (email, full_name, password_hash, role) VALUES "
            "('user@example.com', 'Test User', "
            "  '$2b$12$9xhm2KuN7MsU4PtRqIrSReTpvQ7JPuXUJ3ZXkqDW64pc/2uLD7ojK', 'USER'::user_role), "
            "('admin@example.com', 'Test Admin', "
            "  '$2b$12$mM3ra3qmNnjoDuNDm1cNmO9368A4hRUakR0qkmGD9E5bvpk1R3C6W', 'ADMIN'::user_role)"
        )
    )
    op.execute(sa.text("INSERT INTO accounts (user_id, balance) VALUES (1, 0.00)"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("payments_user_id_idx"), table_name="payments")
    op.drop_index(op.f("payments_transaction_id_idx"), table_name="payments")
    op.drop_index(op.f("payments_account_id_idx"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("accounts_user_id_idx"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
